### ISSUE TITLE
Plugin won't activate with parse error.

### ISSUE THREAD

**Issue by lewisl** [cloudinary/cloudinary_wordpress#25] opened 2018-06-10 20:58 UTC
Parse error: syntax error, unexpected '[' in /home/lewislev/public_html/bikeacrossamerica/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/cloudinary.php on line 624

Wordpress 4.9.6

Not doing anything except installing and trying to activate.

Frustrating.

**Comment by shirlymanor** [comment] 2018-06-12 01:21
In order to provide a better feedback can you please specify the plugin version?

**Comment by scarletish** [comment] 2018-07-29 08:35
@lewisl @shirlymanor 
I receive the same error upon activating:
Cloudinary Version 1.1.10 
WordPress 4.9.7

**Comment by idobarnoam** [comment] 2018-07-29 09:13
@lewisl @scarletish As this might be related to the specific environment you have, could you open a request at Cloudinary@support.com so we could take a closer look?

If you could specify any plugins you have installed it would also help us to find the root cause.

**Comment by roeeba** [comment] 2018-08-28 07:17
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2018-08-28 07:17 UTC
Labels: question
