### ISSUE TITLE
Plugin unable to handle chinese characters in image names

### ISSUE THREAD

**Issue by pepoandra** [cloudinary/cloudinary_wordpress#651] opened 2022-01-05 16:36 UTC
Hello, Cloudinary friends.

We recently installed version 3.0.0 of the plugin, 
running on the docker image  wordpress:5.8.1-php7.4-apache

The problem is that when images with a filename in chinese characters are uploaded, they don't get synced. It seems that the plugin removes all the characters except for the _.extension_ and then it fails to upload.

Example [here](https://res.cloudinary.com/ssenseweb/images/v1641400254/Screen-Shot-2022-01-05-at-11.29.22-AM/Screen-Shot-2022-01-05-at-11-29-22-AM-png?_i=AA)

This is not a blocker for us, but it does make the process more cumbersome, given that we need to rename the images before upload & then update the names on WordPress after. 

Was wondering if you were aware of this issue and whether its realistic to expect a fix in the minor versions to come.

Thanks for your time & I'm available to troubleshoot this any time you want.

**Comment by Vdeub-cloudinary** [comment] 2022-01-05 17:27
Hi @pepoandra, 
Do you mind sharing the file you are trying to upload? What bothers me is that WordPress also shows an empty filename whereas it shouldn't and I'd like to reproduce it on my own instance. Thanks!

**Comment by pepoandra** [comment] 2022-01-06 15:44
this is the image. I don't know if uploading to github would change it in any way. 

![比肩而行](https://user-images.githubusercontent.com/9003029/148409413-382d37db-4904-4ee0-af32-db5e9b047ef9.png)

Let me know what else do you need.

**Comment by Vdeub-cloudinary** [comment] 2022-01-06 16:26
@pepoandra no need indeed. It is working for me because I have a folder in my settings. Since you don't have any, the `public_id` is blank. We may have a code snippet to fix this in the meantime I'll raise a ticket internally to get this code and make sure it is fixed asap. Thanks!

**Comment by pepoandra** [comment] 2022-01-06 16:27
Great, thanks!

Please keep me posted of any updates.

Thanks a lot for the quick reply. Greatly appreciated.

**Comment by pepoandra** [comment] 2022-01-26 20:23
@Vdeub-cloudinary is this issue solved in version 3.0.1 (?

**Comment by Vdeub-cloudinary** [comment] 2022-01-27 08:59
@pepoandra - this issue will be fixed in `3.0.2`.

**Comment by Vdeub-cloudinary** [comment] 2022-03-08 16:54
Hi @pepoandra we just released `3.0.2` that fixes the issue! Please give it a try and let me know if you still encounter the issue.

**Closed** 2023-05-28 12:30 UTC
Labels: bug
